### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by ckorn** [lbalazscs/Pixelitor#1]
Hi,

there has been a request to published Pixelitor for Ubuntu.

Now I have problems creating a jar file from source. There are no build instructions.

Tried to compile the sources but I don't know how to create the jar file:
```
$ find src/main -name "*.java" > sources.txt
$ javac -classpath "/usr/share/java/junit-3.8.2.jar:/usr/share/java/openjfx/jre/lib/ext/jfxrt.jar:." @sources.txt
```

**Comment by lbalazscs** [comment]
Hi Christoph,

1) I always upload jar files to
https://sourceforge.net/projects/pixelitor/files/

2) If you want to re-create the jar yourself, the best way is to use the
Maven build tool. I see now that I forgot to include the Maven
configuration file into the source zip file (it will be included in the
next version), but you can find it at
https://github.com/lbalazscs/Pixelitor/blob/master/pom.xml (I am also
attaching it). Let me know if you need help with Maven.

Compiling form the command line should also work, but it is somewhat
tricky. Actually (as you can see in the maven config file) junit is only a
test dependency, needed only for the files under src/test, but these files
don't have to be included in the distribution jar. On the other hand it is
important that resource files such as images are included in the right
position. Also the manifest file in the jar should be set up. JavaFX is
included in Java 8, and Pixelitor needs Java 8 anyway, so explicitly
putting jfxrt.jar on the classpath should not be necessary.

Regards,
Laszlo

**Comment by ckorn** [comment]
The build using maven fails:
```
$ mvn -X
Apache Maven 3.0.5
Maven home: /usr/share/maven
Java version: 1.8.0_40-internal, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: de_DE, platform encoding: UTF-8
OS name: "linux", version: "3.16.0-34-generic", arch: "amd64", family: "unix"
[INFO] Error stacktraces are turned on.
[DEBUG] Reading global settings from /usr/share/maven/conf/settings.xml
[DEBUG] Reading user settings from /home/korn/.m2/settings.xml
[DEBUG] Using local repository at /home/korn/.m2/repository
[DEBUG] Using manager EnhancedLocalRepositoryManager with priority 10 for /home/korn/.m2/repository
[INFO] Scanning for projects...
[DEBUG] Extension realms for project pixelitor:Pixelitor:jar:3.0.1: (none)
[DEBUG] Looking up lifecyle mappings for packaging jar from ClassRealm[plexus.core, parent: null]
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for pixelitor:Pixelitor:jar:3.0.1
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-jar-plugin is missing. @ line 40, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.099s
[INFO] Finished at: Wed Apr 15 18:38:39 UTC 2015
[INFO] Final Memory: 5M/121M
[INFO] ------------------------------------------------------------------------
[ERROR] No goals have been specified for this build. You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-clean, clean, post-clean, pre-site, site, post-site, site-deploy. -> [Help 1]
org.apache.maven.lifecycle.NoGoalSpecifiedException: No goals have been specified for this build. You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-clean, clean, post-clean, pre-site, site, post-site, site-deploy.
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:104)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoGoalSpecifiedException
```

**Comment by lbalazscs** [comment]
The error message "No goals have been specified for this build." means that
you need to specify a "goal" for Maven. If you want to build a jar, the
"package" goal should be fine. So the command should be:

mvn package

You should start this command in the same directory as the pom.xml, and the
src directory (with the source code) should be a subdirectory here. Maven
should create a target subdirectory here, and the jar file should be
generated in this target subdirectory. You can ignore the
"'build.plugins.plugin.version' for
org.apache.maven.plugins:maven-jar-plugin is missing." warning.

**Comment by ckorn** [comment]
Ok, the compilation succeeded. But the test fail and there is no jar file created. But I think its first created after the test succeed.

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Forking command line: /bin/sh -c cd /home/korn/packages/pixerlator/pixelitor-3.0.1 && /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -jar /home/korn/packages/pixerlator/pixelitor-3.0.1/target/surefire/surefirebooter3373820602212163096.jar /home/korn/packages/pixerlator/pixelitor-3.0.1/target/surefire/surefire9128733528798205114tmp /home/korn/packages/pixerlator/pixelitor-3.0.1/target/surefire/surefire9143216909884758340tmp
Running pixelitor.CompositionTest
Tests run: 50, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.464 sec
Running pixelitor.CompositionCreationTest
Tests run: 7, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.124 sec <<< FAILURE!
Running pixelitor.layers.ContentLayerTest
Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.014 sec
Running pixelitor.layers.LayerTest
Tests run: 11, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.042 sec
Running pixelitor.layers.ImageLayerTest
Tests run: 26, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.028 sec
Running pixelitor.AssertJSwingTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.001 sec

Results :

Tests in error: 
  testReadJPEG(pixelitor.CompositionCreationTest): com.sun.imageio.plugins.jpeg.JPEGImageReader.initReaderIDs(Ljava/lang/Class;Ljava/lang/Class;Ljava/lang/Class;)V

Tests run: 105, Failures: 0, Errors: 1, Skipped: 1

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 12.193s
[INFO] Finished at: Thu Apr 16 17:21:59 UTC 2015
[INFO] Final Memory: 22M/362M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.10:test (default-test) on project Pixelitor: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/korn/packages/pixerlator/pixelitor-3.0.1/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.10:test (default-test) on project Pixelitor: There are test failures.
```

This is the `pixelitor.CompositionCreationTest.txt` file:
```
-------------------------------------------------------------------------------
Test set: pixelitor.CompositionCreationTest
-------------------------------------------------------------------------------
Tests run: 7, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.124 sec <<< FAILURE!
testReadJPEG(pixelitor.CompositionCreationTest)  Time elapsed: 0.019 sec  <<< ERROR!
java.lang.UnsatisfiedLinkError: com.sun.imageio.plugins.jpeg.JPEGImageReader.initReaderIDs(Ljava/lang/Class;Ljava/lang/Class;Ljava/lang/Class;)V
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.initReaderIDs(Native Method)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.<clinit>(JPEGImageReader.java:96)
	at com.sun.imageio.plugins.jpeg.JPEGImageReaderSpi.createReaderInstance(JPEGImageReaderSpi.java:85)
	at javax.imageio.spi.ImageReaderSpi.createReaderInstance(ImageReaderSpi.java:320)
	at javax.imageio.ImageIO$ImageReaderIterator.next(ImageIO.java:529)
	at javax.imageio.ImageIO$ImageReaderIterator.next(ImageIO.java:513)
	at javax.imageio.ImageIO.read(ImageIO.java:1443)
	at javax.imageio.ImageIO.read(ImageIO.java:1308)
	at pixelitor.io.OpenSaveManager.openSimpleFile(OpenSaveManager.java:87)
	at pixelitor.io.OpenSaveManager.createCompositionFromFile(OpenSaveManager.java:79)
	at pixelitor.CompositionCreationTest.testSingleLayerRead(CompositionCreationTest.java:46)
	at pixelitor.CompositionCreationTest.testReadJPEG(CompositionCreationTest.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:53)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:123)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)
```

**Comment by lbalazscs** [comment]
You are right, the jar file is created only if all tests are OK. The
failing test simply tries to read a JPEG file
(src/test/resources/jpeg_test_input.jpg) from the disk.

When I try to search on the internet for the error message
(java.lang.UnsatisfiedLinkError:
com.sun.imageio.plugins.jpeg.JPEGImageReader.initReaderIDs), it seems that
some versions of OpenJDK 8 have a bug which causes this issue, but it
should be already fixed in the newest release:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=760926#45

Please check that you have the latest OpenJDK.

**Comment by ckorn** [comment]
The version in Ubuntu 14.10 is too old.
But 15.04 should contain the fix once it is released:
http://packages.ubuntu.com/vivid/openjdk-8-jdk

Will wait until then. Thanks for your help.

**Comment by ckorn** [comment]
Build succeeded on Ubuntu 15.04.

Just had to remove some tests because they require a X11 display which is not available in the build chroot.
