### ISSUE TITLE
IllegalArgumentException: Window must not be zero with Java 10 and Java 11

### ISSUE THREAD

**Issue by albertsteckermeier** [lbalazscs/Pixelitor#15]
I get the following exception when trying to run Pixelitor using Java 10 and Java 11.

```
Dialogs.showExceptionDialog: Exception in the thread 'AWT-EventQueue-0'
java.lang.ExceptionInInitializerError
	at pixelitor.gui.PixelitorWindow.getInstance(PixelitorWindow.java:151)
	at pixelitor.Pixelitor.createAndShowGUI(Pixelitor.java:101)
	at pixelitor.Pixelitor.lambda$main$0(Pixelitor.java:84)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.IllegalArgumentException: Window must not be zero
	at java.desktop/sun.awt.X11.XAtom.checkWindow(XAtom.java:774)
	at java.desktop/sun.awt.X11.XAtom.getAtomData(XAtom.java:465)
	at java.desktop/sun.awt.X11.XToolkit.getWorkArea(XToolkit.java:805)
	at java.desktop/sun.awt.X11.XToolkit.getInsets(XToolkit.java:881)
	at java.desktop/sun.awt.X11.XToolkit.getScreenInsets(XToolkit.java:869)
	at java.desktop/sun.java2d.SunGraphicsEnvironment.getUsableBounds(SunGraphicsEnvironment.java:260)
	at java.desktop/sun.awt.X11GraphicsEnvironment.getXineramaWindowBounds(X11GraphicsEnvironment.java:390)
	at java.desktop/sun.awt.X11GraphicsEnvironment.getMaximumWindowBounds(X11GraphicsEnvironment.java:314)
	at pixelitor.utils.AppPreferences.loadFramePosition(AppPreferences.java:133)
	at pixelitor.gui.PixelitorWindow.<init>(PixelitorWindow.java:69)
	at pixelitor.gui.PixelitorWindow.<init>(PixelitorWindow.java:45)
	at pixelitor.gui.PixelitorWindow$PixelitorWindowHolder.<clinit>(PixelitorWindow.java:158)
	... 16 more
java.lang.NoClassDefFoundError: Could not initialize class pixelitor.gui.PixelitorWindow$PixelitorWindowHolder
	at pixelitor.gui.PixelitorWindow.getInstance(PixelitorWindow.java:151)
	at pixelitor.utils.test.RandomGUITest.stop(RandomGUITest.java:217)
	at pixelitor.gui.utils.Dialogs.showExceptionDialog(Dialogs.java:193)
	at pixelitor.gui.GUIMessageHandler.showException(GUIMessageHandler.java:79)
	at pixelitor.utils.Messages.showException(Messages.java:69)
	at pixelitor.ExceptionHandler.uncaughtException(ExceptionHandler.java:48)
	at java.base/java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1055)
	at java.base/java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1050)
	at java.desktop/java.awt.EventDispatchThread.processException(EventDispatchThread.java:222)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:214)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
Java 10 version:
```
java version "10.0.2" 2018-07-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)
```
Java 11 version:
```
java version "11" 2018-09-25
Java(TM) SE Runtime Environment 18.9 (build 11+28)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11+28, mixed mode)
```

**Comment by lbalazscs** [comment]
Thank you for the bug report. Sadly this seems to be a bug in Java on Linux when using multi-monitor setups (therefore there's not much I can do about it), see for example https://bugs.openjdk.java.net/browse/JDK-8204646

I recommend using Java 8 as long as the Java bug is not fixed.

**Comment by lbalazscs** [comment]
Now I see that possibly they managed to port this bug to Java 8 (starting from 8u172) as well...  (I can't reproduce anything as I use a single monitor.)

**Comment by lbalazscs** [comment]
I was able to reproduce the issue with three simulated monitors in a VirtualBox virtual machine. 
The commit 8bc7e1305a28073c3b2d23aebbb121fa1d72a9a7 is a workaround and should fix the problem. 
You can build a jar with Maven, or wait a few days, as version 4.2.0 should be released soon.

**Comment by albertsteckermeier** [comment]
Thanks a lot for the fix lbalazscs.
