### ISSUE TITLE
Build Failure on Java 11

### ISSUE THREAD

**Issue by LucasTheCure** [lbalazscs/Pixelitor#93]
When run: "mvn package"

java --version
openjdk 11.0.4 2019-07-16
OpenJDK Runtime Environment (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3)
OpenJDK 64-Bit Server VM (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3, mixed mode, sharing)

one of the errors:

testMultipleSubPaths(pixelitor.tools.pen.PathBuilderTest)  Time elapsed: 0.438 sec  <<< FAILURE!
java.lang.AssertionError: 
Expecting:
  <["Finish Subpath",
    "Subpath Start",
    "Add Anchor Point",
    "Add Anchor Point",
    "Close Subpath"]>
to contain exactly (and in same order):
  <["Subpath Start",
    "Add Anchor Point",
    "Add Anchor Point",
    "Finish Subpath",
    "Subpath Start",
    "Add Anchor Point",
    "Add Anchor Point",
    "Close Subpath"]>
but could not find the following elements:
  <["Subpath Start", "Add Anchor Point", "Add Anchor Point"]>

        at pixelitor.TestHelper.assertHistoryEditsAre(TestHelper.java:392)
        at pixelitor.tools.pen.PathBuilderTest.undoRedoMultipleSubpaths(PathBuilderTest.java:767)
        at pixelitor.tools.pen.PathBuilderTest.testMultipleSubPaths(PathBuilderTest.java:107)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

**Comment by lbalazscs** [comment]
Hi, it's great to see that you are still interested in Pixelitor!

I suspect that that problem is that the history undo levels is not big enough for this test.
The static initializer of pixelitor.history.History sets the the level to 15, which should be enough for all tests. 

```java
    static {
        if (Build.isUnitTesting()) {
            // make sure we have enough undo for the tests
            setUndoLevels(15);
        } else {
            setUndoLevels(AppPreferences.loadUndoLevels());
        }
    }
```

But it seems that somehow the History class was initialized before the setupClass method of PathBuilderTest could call Build.setUnitTestingMode. In the latest commit I call History.setUndoLevels(15) in Build.setUnitTestingMode, so it should overwrite an incorrect level.

Please check again with my latest commit.

**Comment by LucasTheCure** [comment]
After update all tests pass without any issues. Thank you.

**Comment by lbalazscs** [comment]
With 4f6ad787829ebdf20c54a12506f37ade1ea2c452 I also added OpenJDK 11 and OpenJDK 13 to the travis checks, so from now all commits will be checked on three different (Linux) JDKs.
